### PR TITLE
SortCurveLoops that works on curved faces

### PR DESCRIPTION
**Pull request by stenci**
This command asks the user to pick a face, gets its edge loops, sorts all the inner loops together with their outer loop, then creates a label on the first edge of each loop.

I'm an absolute beginner with C#, so I rely on Rider's auto formatting and suggestions to learn both how C# works and the correct formatting style. The result is that my style is inconsistent with the rest of the repository.

You said you [would probably like to share this on the blog](https://forums.autodesk.com/t5/revit-api-forum/is-the-first-edgeloop-still-the-outer-loop/m-p/10243455/highlight/true#M55294), so I copied the code from my add-in to my fork of the_building_coder_samples and added CmdSortCurveLoops. Just in case you like my code, don't mind my style being different from yours (and my code works), here is a pull request.

### CODE REVIEW

**Comment by jeremytammik** [comment]
Wow, that looks utterly fantastic! Thank you ever so much. This may be the first complete pull request adding a new command ever.

**Comment by jeremytammik** [comment]
Pointing out the original discussion thread in the Revit API forum:

https://forums.autodesk.com/t5/revit-api-forum/is-the-first-edgeloop-still-the-outer-loop/m-p/10245491

You show a nice sample model there ... would you like to share that either there or here to verify that it works for others also?

Thank you!

**Comment by jeremytammik** [comment]
I integrated and tested this on my trivial little house model, and it works fine.

**Comment by jeremytammik** [comment]
Looks like the most advanced and useful command of all the sample so far...

**Comment by jeremytammik** [comment]
integrated in release 2021.0.150.25: 

https://github.com/jeremytammik/the_building_coder_samples/compare/2021.0.150.24...2021.0.150.25

**Comment by stenci** [comment]
I attached the Revit file I used for my tests to the forum post. 

I have a semi-unrelated question: after my first pull request (about deleting the GorupType) I was able to fetch upstream and origin without problems. Now I can't understand why it doesn't work. Here is what I'm doing:
```
C:\Users\stefanomenci\source\repos\the_building_coder_samples>git fetch upstream

C:\Users\stefanomenci\source\repos\the_building_coder_samples>git fetch origin

C:\Users\stefanomenci\source\repos\the_building_coder_samples>git log --pretty="format:%ad  %s" --date=short
2021-04-17  Merge branch 'master' of https://github.com/jeremytammik/the_building_coder_samples
2021-04-17  Add CmdSortCurveLoops
2021-04-15  whitespace
```

As you can see the latest commits in upstream don't show up (I see you are already working on the 2012 upgrade). 
Any idea what I am doing wrong?

**Comment by stenci** [comment]
Here is a related question: do you know what the correct value for Epsilon should be?

In some CAD it's a global parameter, in some it's a document parameter, in some it's an entity parameter. 
Is there a suggested tolerance value in Revit?

In ThinkDesign for example every entity inherits its tolerance from a document parameter, then every operation executed on the entity will update its tolerance. For example trimming two perpendicular lines will not change their tolerance, but trimming two lines at 1 degree from each other may increase it, because the intersection area is defined by the intersection between the areas around the lines as large as their tolerance. The size of the red area in the snapshot will be the line's tolerance after the trim. (I am using straight lines to describe the concept, I know this happens on 3D complex geometries, I don't know if it really happens on 2D lines.)
image

**Comment by jeremytammik** [comment]
Thank you for the sample model.

Re the pull request: Sorry, no idea. I am a very minimalistic and simplistic github user. If I have a problem with anything, I generally do stuff like delete the local repository copy and clone a new copy from scratch from github.

Re epsilon: wow, the ThinkDesign approach sounds very advanced indeed. How nice of them to take that so seriously. I am not aware of any such advanced approach. In AutoCAD it is a bit better than Revit. In Revit it mat be good internally, but I see very little useful access to fuzziness in the Revit API. In Revit, I generally use something like 1.e-9 for numeric calculations and 1 mm or 1/16 of an inch for length comparisons in the BIM. Very simplistic there as well, I'm afraid.

My approach to eliminate rounding problems in Revit BIM geometry is to switch from double number lengths in imperial feet to integer-valued lengths in mm. Then, I can often use exact comparisons.

Sorry for the rather simplistic answers all around...

**Pull request merged**
